# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Enter_First_Name', models.CharField(default='', max_length=30)),
                ('Enter_Last_Name', models.CharField(default='', max_length=30)),
                ('Enter_Email_Id', models.EmailField(default='', max_length=100)),
                ('Enter_Contact_No', models.BigIntegerField(default='0')),
                ('Vehicle_Type', models.CharField(choices=[('Make', 'Make'), ('Acura', 'Acura'), ('Audi', 'Audi'), ('BMW', 'BMW'), ('FORD', 'HONDA'), ('HONDA', 'HONDA'), ('FEEP', 'FEEP'), ('LEXUS', 'LEXUS'), ('SUZUKI', 'SUZUKI')], default='XYZ', max_length=40)),
                ('Year_Old', models.CharField(choices=[('2007', '2007'), ('2008', '2008'), ('2009', '2009'), ('2010', '2010'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017')], default='XYZ', max_length=40)),
                ('Car_Model_Type', models.CharField(choices=[('A3 QUATTRO', 'A3 QUATTRO'), ('A3 TDI', 'A3 TDI'), ('A4', 'A4'), ('A4 QUATTRO', 'A4 QUATTRO'), ('A5 QUATTRO', 'A5 QUATTRO'), ('A6', 'A6')], default='XYZ', max_length=40)),
                ('Car_Submodel_Type', models.CharField(choices=[('Sports', 'Sports'), ('SE', 'SE'), ('Limited Edition', 'Limited Edition')], default='abc', max_length=40)),
                ('Car_Mileage', models.CharField(choices=[('less then 10K', 'less then 10K'), ('30K', '30K'), ('40K', '40K'), ('More Than 40K', 'More Than 40K')], default='20km', max_length=30)),
                ('Service_Request', multiselectfield.db.fields.MultiSelectField(choices=[(' Oil &amp; Filter Change', ' Oil &amp; Filter Change'), ('Starting &amp; Charging/Battery', 'Starting &amp; Charging/Battery'), ('Complete Vehicle Inspection', 'Complete Vehicle Inspection'), (' Tyre Replacement', ' Tyre Replacement'), (' State Inspection', ' State Inspection'), ('Wiper Blades', 'Wiper Blades'), ('Tyre Rotation', 'Tyre Rotation'), ('Air Filter &amp; Cabin Air Filter', 'Air Filter &amp; Cabin Air Filter'), ('Lighting &amp; Bulbs', 'Lighting &amp; Bulbs'), (' Wheel Balance', ' Wheel Balance')], default='', max_length=217)),
            ],
        ),
    ]
