# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('aloautoworks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquerydata',
            name='Enter_Contact_No',
            field=models.BigIntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='userquerydata',
            name='Service_Request',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(' Oil  Filter Change', ' Oil  Filter Change'), ('Starting  Charging/Battery', 'Starting  Charging/Battery'), ('Complete Vehicle Inspection', 'Complete Vehicle Inspection'), (' Tyre Replacement', ' Tyre Replacement'), (' State Inspection', ' State Inspection'), ('Wiper Blades', 'Wiper Blades'), ('Tyre Rotation', 'Tyre Rotation'), ('Air Filter  Cabin Air Filter', 'Air Filter  Cabin Air Filter'), ('Lighting Bulbs', 'Lighting &amp; Bulbs'), (' Wheel Balance', ' Wheel Balance')], default='', max_length=196),
        ),
    ]
